### ISSUE TITLE
Add a  "Create a proxy link" 

### ISSUE THREAD

**Issue by haitzlm** [uclibs/proxy_user#3]
2. Take a look at this page, specifically the Create a Library Proxy Link: 

https://library.unt.edu/proxy-tools/

We'd like the same functionality.

**Comment by scherztc** [comment]
https://library.cuanschutz.edu/ezproxy-campus-link-generator

AEM?  Javascript or App Server
Javascript text substitution

**Comment by scherztc** [comment]
```

<script language="javascript">
--
  | <!--//--><![CDATA[// ><!--
  |  
  | function makeLink() {
  | var oin=document.frm.intext;
  | var oout=document.frm.outtext;
  | var intxt=oin.value;
  | if(intxt.length==0) {
  | oin.focus();
  | alert("No URL entered!");
  | }
  |  
  | else {
  | var prep="https://proxy.hsl.ucdenver.edu/login?url=";
  | var rc=intxt.indexOf('https://proxy.hsl.ucdenver.edu/login?url=')
  | var rd=intxt.indexOf('.proxy.hsl.ucdenver.edu')
  | var wellFormedHttp=intxt.indexOf('http://')
  | var wellFormedHttps=intxt.indexOf('https://')
  | if(wellFormedHttp=='0'\|\|wellFormedHttps=='0'){
  | //alert("Matched http://"+wellFormed);
  | //}
  | if(rc==-1) {
  | if(rd==-1){
  | oout.value=prep+intxt;
  | oout.focus();
  | oout.select();
  | }
  | else{
  | alert("That is a translated EzProxy URL and shouldn't be used. Click OK to fix");
  | intxt = intxt.replace(/.proxy.hsl.ucdenver.edu/g,"")
  | oout.value=prep+intxt;
  | oin.focus();
  | oin.select();
  | }
  | }
  | else {
  | alert("That is already an EzProxy prefixed URL, so no change is needed");
  | oout.value="";
  | oin.focus();
  | oin.select();
  | }
  | }
  | else{
  | alert("The URL source URL doesn't start with http:// or https:// or contains multiple entries, please enter a valid URL like https://someaddress.com");
  | oout.value="";
  | oin.focus();
  | oin.select();
  | }
  | }
  |  
  | }
  |  
  | //--><!]]>
  | </script><form name="frm" id="frm">
  | <h3>1. Copy and paste your source URL here:</h3>
  | <p><textarea aria-label="Source URL" cols="60" name="intext" rows="5"></textarea><br />
  | </p>
  | <h3>2. Click this:</h3>
  | <p><input onclick="makeLink();" type="button" value="CREATE LINK" /><br />
  | </p>
  | <h3>3. Copy, use, and share the resulting link</h3>
  | <p><textarea aria-label="Resulting Link" cols="60" name="outtext" rows="5"></textarea><br /><input type="reset" value="CLEAR FORM" /></p>
  | <h3>URL Encoding</h3>
  | <p>As you look at URLs for library resources, you will typically see many encoded URLs (these typically have a lot of % signs and other characters hard for us to read). For example the text string http:// may show up as http%3a%2f%2f.</p>
  | <p>If you want a shorter a URL there are many great, free websites (<a href="https://meyerweb.com/eric/tools/dencoder/" target="_blank">like Meyerweb URL Decoder/Encoder</a>) that can decode or encode URLs as you like. Although encoding is often done for web security reasons, for most end users, URLs whether encoded or not should not affect the proxy function (if proxy is included on the link) nor should encoding affect the ability of URLs to link correctly to their destinations.</p>
  | <h3>URL Shorteners</h3>
  | <p>URL shorteners (such as bitly.com and tinyURL.com) are really just aliases for real URLs. They can be used for proxied URLs, however it should be noted that "URLs are not forever" and shortened links may provide even less information for users if and when the link fails than "real" unmodified URLs.</p>
  | </form>

```

**Comment by scherztc** [comment]
@hortongn Lisa has it done.  She is checking with Web Group to see where it should link from.  https://libraries.uc.edu/proxylinkgenerator.html

**Comment by haitzlm** [comment]
Thanks!

**Comment by kjhiller** [comment]
The page is up as part of a draft "Help and Troubleshooting" page Elna is working on:  https://guides.libraries.uc.edu/c.php?g=1042067.  We discussed a few modifications; is this the appropriate place to request them?

**Comment by hortongn** [comment]
Yes!  Go ahead and put your request in these comments.

**Comment by kjhiller** [comment]
I would propose:
1.  Changing box 1 so that it does not return an error if the URL does not start with http or https.  This was already done on the prototype page at http://libapps.libraries.uc.edu/proxyuser.
2.  Adding buttons below box 3 to (a) automatically copy the URL to clipboard, and (b) go to the new URL, keeping (c) as Clear Form.
3.  I also think we could remove the URL Encoding and URL Shortening sections, or greatly abridge them.
4.  This is getting into more into presentation than coding, but after I showed her https://library.unt.edu/proxy-tools, Susan Banoun said "Love the ‘proxy-ify it’ – we should add this."

**Comment by scherztc** [comment]
Followed up with @lisa3711  on August 17th.

**Comment by scherztc** [comment]
@lisa3711 :  The following changes are still needed:

1.  Changing box 1 so that it does not return an error if the URL does not start with http or https. This was already done on the prototype page at http://libapps.libraries.uc.edu/proxyuser

2. Adding buttons below box 3 to (a) automatically copy the URL to clipboard, and (b) go to the new URL, keeping (c) as Clear Form.

There is also concern about why there are two pages : 

https://libraries.uc.edu/proxylinkgenerator.html and it does not work right.  the other is at https://guides.libraries.uc.edu/c.php?g=1042067

**Comment by scherztc** [comment]
https://guides.libraries.uc.edu/c.php?g=1042067

**Comment by haitzlm** [comment]
This is now working and up on https://libraries.uc.edu/off-campus-access/Tools.html
